# Generated by Django 4.2 on 2023-04-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.FloatField()),
                ('category', models.CharField(choices=[('PH', 'Phone'), ('TV', 'Television'), ('TA', 'Tablet'), ('PC', 'Personal computer'), ('WA', 'Watches')], max_length=2)),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
