# Generated by Django 4.2 on 2023-05-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_newcategory_remove_customer_locality_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCategory',
        ),
    ]
